services:
  pgadmin:
    image: "dpage/pgadmin4:latest"
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    volumes:
      - "./pgadmin/data:/var/lib/pgadmin"
    ports:
      - "${PGADMIN_PORT:-8112}:80"

  pgvector:
    image: "pgvector/pgvector:pg17"
    platform: "${DOCKER_PLATFORM:-linux/arm64}"
    container_name: pgvector
    build:
      context: .
      dockerfile: Dockerfile.pgvector
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements,auto_explain"
      - "-c"
      - "compute_query_id=on"
      - "-c"
      - "pg_stat_statements.track=all"
      - "-c"
      - "auto_explain.log_min_duration=300ms"
      - "-c"
      - "auto_explain.log_analyze=on"
      - "-c"
      - "auto_explain.log_buffers=on"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - "./pgvector/data:/var/lib/postgresql/data"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
